name: Lint Docs

on:
  push:
    branches-ignore:
      - master
      - main
  pull_request:
    branches:
      - master
      - main

jobs:
  build:
    name: Lint Markdown
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout Code
        uses: actions/checkout@main

      - name: Setup Node
        uses: actions/setup-node@main
        with:
          node-version: 'lts/*'

      - name: Install Linter
        run: npm i --no-save markdownlint-cli2

      - name: Add Matcher
        uses: xt0rted/markdownlint-problem-matcher@b643b0751c371f357690337d4549221347c0e1bc
      
      - name: Lint Docs
        run: ./node_modules/.bin/markdownlint-cli2-config .github/md-lint.yaml
      
      - name: Process results
        if: success() || failure()
        uses: xt0rted/markdownlint-problem-matcher@b643b0751c371f357690337d4549221347c0e1bc
        with:
          action: remove

